# OpenShift Pipelines Operator
# Note: The OpenShift Pipelines Operator also creates some CRs automatically after installation. 
#       The OperatorPolicy with "mustnothave" doesn't remove these instances, so setting "disabled: true" can't be used for a proper uninstallation. Should use the UI instead.
operator:
  name: openshift-pipelines-operator-rh
  namespace: openshift-pipelines-operator
  channel: latest
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  
# List all available operator versions
# oc get packagemanifest openshift-pipelines-operator-rh -o json | jq -r  '.status.channels[] | select(.name == "latest") | .entries | reverse | .[].name'
# oc get packagemanifest openshift-pipelines-operator-rh -o jsonpath='{range .status.channels[?(@.name == "latest")].entries[::]}- {.name}{"\n"}{end}' | tac
  versions:
    - openshift-pipelines-operator-rh.v1.15.0
    - openshift-pipelines-operator-rh.v1.15.1
    - openshift-pipelines-operator-rh.v1.15.2
    - openshift-pipelines-operator-rh.v1.15.3
    - openshift-pipelines-operator-rh.v1.15.4
    - openshift-pipelines-operator-rh.v1.16.0
    - openshift-pipelines-operator-rh.v1.16.1
    - openshift-pipelines-operator-rh.v1.16.2
    - openshift-pipelines-operator-rh.v1.16.3
    - openshift-pipelines-operator-rh.v1.16.4
    - openshift-pipelines-operator-rh.v1.17.0
    - openshift-pipelines-operator-rh.v1.17.1
    - openshift-pipelines-operator-rh.v1.17.2
    - openshift-pipelines-operator-rh.v1.18.0
    - openshift-pipelines-operator-rh.v1.18.1
    - openshift-pipelines-operator-rh.v1.19.0
    - openshift-pipelines-operator-rh.v1.19.1
    - openshift-pipelines-operator-rh.v1.19.2
    - openshift-pipelines-operator-rh.v1.19.3
    - openshift-pipelines-operator-rh.v1.19.4
    - openshift-pipelines-operator-rh.v1.20.0
    - openshift-pipelines-operator-rh.v1.20.1
    - openshift-pipelines-operator-rh.v1.20.2
    - openshift-pipelines-operator-rh.v1.20.3
    - openshift-pipelines-operator-rh.v1.20.4
    - openshift-pipelines-operator-rh.v1.20.5
    - openshift-pipelines-operator-rh.v1.21.0
    - openshift-pipelines-operator-rh.v1.21.1
    - openshift-pipelines-operator-rh.v1.21.2
    - openshift-pipelines-operator-rh.v1.22.0
    - openshift-pipelines-operator-rh.v1.22.1
    - openshift-pipelines-operator-rh.v1.22.2
    - openshift-pipelines-operator-rh.v1.22.3

# Actual allowed versions to upgrade to are the latest within z-streams:
# - openshift-pipelines-operator-rh.v1.16.4
# - openshift-pipelines-operator-rh.v1.17.2
# - openshift-pipelines-operator-rh.v1.18.1
# - openshift-pipelines-operator-rh.v1.19.4
# - openshift-pipelines-operator-rh.v1.20.5
# - openshift-pipelines-operator-rh.v1.21.2
# - openshift-pipelines-operator-rh.v1.22.3

# Set the environment during deployment with "--set env=qa"
# helm template openshift-pipelines-operator ./operatorpolicy-directly-helm --set env=qa -f ./operatorpolicy-directly-helm/values-pipelines.yaml
environments:
  - name: qa
    targetVersion: openshift-pipelines-operator-rh.v1.15.0
  - name: uat
    targetVersion: openshift-pipelines-operator-rh.v1.15.0
    disabled: true
