{{- range .Values.environments }} 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.operator.namespace }}-{{ .name }}
  namespace: open-cluster-policies
data:
  targetVersion: '{{ .targetVersion }}'
  disabled: '{{ .disabled }}'
{{- end }}