{{- range .Values.environments }} 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-pipelines-operator-{{ .name }}
  namespace: open-cluster-policies
data:
  targetVersion: '{{ .targetVersion }}'
  disabled: '{{ .disabled }}'
{{- end }}