apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .Values.operator.namespace }}
  namespace: open-cluster-policies
placementRef:
  name: {{ .Values.operator.namespace }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ .Values.operator.namespace }}
    apiGroup: policy.open-cluster-management.io
    kind: Policy