apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .Values.operator.namespace }}
  namespace: open-cluster-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .Values.operator.namespace }}-ns
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            # Not adding "mustnothave" here to avoid deleting something accidentally
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .Values.operator.namespace }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: {{ .Values.operator.namespace }}
        spec:
          remediationAction: enforce
          complianceType: '{{ "{{hub" }} if (fromConfigMap "" (printf "{{ .Values.operator.namespace }}-%s" .ManagedClusterLabels.env) "disabled" | default false | toBool) {{ "hub}}mustnothave{{hub else hub}}musthave{{hub end hub}}" }}'
          severity: critical
          subscription:
            name: {{ .Values.operator.name }}
            namespace: {{ .Values.operator.namespace }}
            source: {{ .Values.operator.source }}
            sourceNamespace: {{ .Values.operator.sourceNamespace }}
            channel: {{ .Values.operator.channel }}
            startingCSV: '{{ "{{hub" }} fromConfigMap "" (printf "{{ .Values.operator.namespace }}-%s" .ManagedClusterLabels.env) "targetVersion" {{ "hub}}" }}'
          removalBehavior:
            # Keep (default) or Delete (make sure that all CR instances are deleted separately first)
            customResourceDefinitions: Keep
          upgradeApproval: Automatic
          versions:
          {{- $exprs := include "versionsPerEnvironment" (dict "environments" .Values.environments "versions" .Values.operator.versions) | fromJsonArray -}}
          {{- range $exprs }}
            - {{ . }}
          {{- end }}
          
            
            