
operator:
  name: openshift-pipelines-operator-rh
  namespace: openshift-pipelines-operator
  channel: latest
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  
  # List all available operator versions
  # oc get packagemanifest openshift-pipelines-operator-rh -o json | jq -r '.status.channels[] | .name as $channel | .entries[] | [$channel, .name, .version] | @tsv'
  versions:
    - openshift-pipelines-operator-rh.v1.14.0
    - openshift-pipelines-operator-rh.v1.14.1
    - openshift-pipelines-operator-rh.v1.14.2
    - openshift-pipelines-operator-rh.v1.14.3
    - openshift-pipelines-operator-rh.v1.14.4
    - openshift-pipelines-operator-rh.v1.14.5
    - openshift-pipelines-operator-rh.v1.14.6
    - openshift-pipelines-operator-rh.v1.15.0
    - openshift-pipelines-operator-rh.v1.15.1
    - openshift-pipelines-operator-rh.v1.15.2
    - openshift-pipelines-operator-rh.v1.15.3
    - openshift-pipelines-operator-rh.v1.15.4
    - openshift-pipelines-operator-rh.v1.16.0
    - openshift-pipelines-operator-rh.v1.16.1
    - openshift-pipelines-operator-rh.v1.16.2
    - openshift-pipelines-operator-rh.v1.16.3
    - openshift-pipelines-operator-rh.v1.16.4
    - openshift-pipelines-operator-rh.v1.17.0
    - openshift-pipelines-operator-rh.v1.17.1
    - openshift-pipelines-operator-rh.v1.17.2
    - openshift-pipelines-operator-rh.v1.18.0
    - openshift-pipelines-operator-rh.v1.18.1
    - openshift-pipelines-operator-rh.v1.19.0
    - openshift-pipelines-operator-rh.v1.19.1
    - openshift-pipelines-operator-rh.v1.19.2
    - openshift-pipelines-operator-rh.v1.19.3
    - openshift-pipelines-operator-rh.v1.19.4
    - openshift-pipelines-operator-rh.v1.20.0
    - openshift-pipelines-operator-rh.v1.20.1
    - openshift-pipelines-operator-rh.v1.20.2
    - openshift-pipelines-operator-rh.v1.20.3
    - openshift-pipelines-operator-rh.v1.20.4
    - openshift-pipelines-operator-rh.v1.20.5
    - openshift-pipelines-operator-rh.v1.21.0
    - openshift-pipelines-operator-rh.v1.21.1
    - openshift-pipelines-operator-rh.v1.22.0
    - openshift-pipelines-operator-rh.v1.22.1

# Set the environment during deployment with "--set env=qa"
# helm template test ./operatorpolicy-directly-helm --set env=qa
environments:
  - name: qa
    targetVersion: openshift-pipelines-operator-rh.v1.15.4
    disabled: false
  - name: uat
    targetVersion: openshift-pipelines-operator-rh.v1.14.0
    disabled: true
